basePath: /
consumes:
    - application/json
definitions:
    BaseInfo:
        description: The base response data | 基础信息
        properties:
            createdAt:
                description: Create date | 创建日期
                format: int64
                type: integer
                x-go-name: CreatedAt
            deletedAt:
                description: Delete date | 删除日期
                format: int64
                type: integer
                x-go-name: DeletedAt
            id:
                description: ID
                format: uint64
                type: integer
                x-go-name: ID
            updatedAt:
                description: Update date | 更新日期
                format: int64
                type: integer
                x-go-name: UpdatedAt
        type: object
        x-go-package: slash-admin/app/admin/cmd/api/internal/types
    IDPathReq:
        description: Basic id request | 基础id参数请求
        properties:
            ID:
                description: ID
                format: uint64
                type: integer
        required:
            - ID
        type: object
        x-go-package: slash-admin/app/admin/cmd/api/internal/types
    IDReq:
        description: Basic id request | 基础id参数请求
        properties:
            id:
                description: ID
                format: uint64
                type: integer
                x-go-name: ID
        required:
            - id
        type: object
        x-go-package: slash-admin/app/admin/cmd/api/internal/types
    PageReq:
        description: The page request parameters | 列表请求参数
        properties:
            pageNo:
                description: Page number | 第几页
                format: uint64
                type: integer
                x-go-name: PageNo
            pageSize:
                description: Page size | 单页数据行数
                format: uint64
                maximum: 100000
                type: integer
                x-go-name: PageSize
        required:
            - pageNo
            - pageSize
        type: object
        x-go-package: slash-admin/app/admin/cmd/api/internal/types
    RoleInfo:
        description: Create or update role information params | 创建或更新角色信息参数
        properties:
            createAt:
                description: Create time | 创建日期
                format: int64
                type: integer
                x-go-name: CreateAt
            defaultRouter:
                description: Role's default page | 角色默认管理页面
                maxLength: 20
                type: string
                x-go-name: DefaultRouter
            id:
                description: Role ID | 角色 ID
                format: uint64
                maximum: 1000
                type: integer
                x-go-name: Id
            name:
                description: Role Name | 角色名
                maxLength: 20
                type: string
                x-go-name: Name
            orderNo:
                description: Role's sorting number | 角色排序
                format: uint32
                maximum: 1000
                type: integer
                x-go-name: OrderNo
            remark:
                description: Role remark | 角色备注
                maxLength: 200
                type: string
                x-go-name: Remark
            status:
                description: Role status | 角色状态
                format: uint32
                maximum: 20
                type: integer
                x-go-name: Status
            value:
                description: Role value | 角色值
                maxLength: 10
                type: string
                x-go-name: Value
        required:
            - id
            - name
            - value
            - defaultRouter
            - status
            - remark
            - orderNo
            - createAt
        type: object
        x-go-package: slash-admin/app/admin/cmd/api/internal/types
    SetBooleanStatusReq:
        description: The request params of setting boolean status | 设置状态参数
        properties:
            id:
                description: ID
                format: uint64
                type: integer
                x-go-name: Id
            status:
                description: Status code | 状态码
                format: uint32
                type: integer
                x-go-name: Status
        required:
            - id
            - status
        type: object
        x-go-package: slash-admin/app/admin/cmd/api/internal/types
    SetStatusReq:
        description: The request params of setting role status | 设置角色状态参数
        properties:
            id:
                description: ID
                format: uint64
                maximum: 1000
                type: integer
                x-go-name: Id
            status:
                description: Status code | 状态码
                format: uint32
                maximum: 20
                type: integer
                x-go-name: Status
        required:
            - id
            - status
        type: object
        x-go-package: slash-admin/app/admin/cmd/api/internal/types
    UUIDReq:
        description: Basic UUID request | 基础UUID参数请求
        properties:
            UUID:
                description: UUID
                maxLength: 36
                type: string
        required:
            - UUID
        type: object
        x-go-package: slash-admin/app/admin/cmd/api/internal/types
host: localhost:9100
info:
    description: 'Description: core service'
    title: System Name
    version: 0.0.1
paths:
    /core/health:
        get:
            description: '"检查系统状态"'
            operationId: HealthCheck
            summary: '"Check the system status | 检查系统状态"'
            tags:
                - core
    /core/init/database:
        get:
            description: '"初始化数据库"'
            operationId: InitDatabase
            responses:
                "200":
                    $ref: '#/responses/SimpleMsgResp'
            summary: '"Initialize database | 初始化数据库"'
            tags:
                - core
    /role:
        delete:
            description: '"删除角色信息"'
            operationId: DeleteRole
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/IDReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/SimpleMsgResp'
            summary: '"Delete role information | 删除角色信息"'
            tags:
                - role
        post:
            description: '"创建或更新角色"'
            operationId: CreateOrUpdateRole
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/RoleInfo'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/SimpleMsgResp'
            summary: '"Create or update role information | 创建或更新角色"'
            tags:
                - role
    /role/list:
        post:
            description: '"获取角色列表"'
            operationId: GetRoleList
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/PageReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/RoleListResp'
            summary: '"Get role list | 获取角色列表"'
            tags:
                - role
    /role/status:
        post:
            description: '"设置角色状态"'
            operationId: SetRoleStatus
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/SetStatusReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/SimpleMsgResp'
            summary: '"Set role status | 设置角色状态"'
            tags:
                - role
    /user:
        delete:
            description: '"删除用户信息"'
            operationId: DeleteUser
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/IDReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/SimpleMsg'
            summary: '"Delete user information | 删除用户信息"'
            tags:
                - user
        post:
            description: '"新增或更新用户"'
            operationId: CreateOrUpdateUser
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/CreateOrUpdateUserReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/SimpleMsg'
            summary: '"Create or update user''s information | 新增或更新用户"'
            tags:
                - user
    /user/change-password:
        post:
            description: '"修改用户密码"'
            operationId: ChangePassword
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/ChangePasswordReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/SimpleMsg'
            summary: '"Change Password | 修改密码"'
            tags:
                - user
    /user/info:
        get:
            description: '"获取用户基本信息"'
            operationId: GetUserInfo
            responses:
                "200":
                    $ref: '#/responses/GetUserInfoResp'
            summary: '"Get user basic information | 获取用户基本信息"'
            tags:
                - user
    /user/list:
        post:
            description: '"获取用户列表"'
            operationId: GetUserList
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/GetUserListReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/UserListResp'
            summary: '"Get user list | 获取用户列表"'
            tags:
                - user
    /user/login:
        post:
            description: '"登录"'
            operationId: Login
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/LoginReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/LoginResp'
            summary: '"Log in | 登录"'
            tags:
                - user
    /user/logout:
        get:
            description: '"退出登陆"'
            operationId: Logout
            responses:
                "200":
                    $ref: '#/responses/SimpleMsg'
            summary: '"Log out | 退出登陆"'
            tags:
                - user
    /user/perm:
        get:
            description: '"获取用户权限码"'
            operationId: GetUserPermCode
            responses:
                "200":
                    $ref: '#/responses/PermCodeResp'
            summary: '"Get user''s permission code | 获取用户权限码"'
            tags:
                - user
    /user/profile:
        get:
            description: '"获取用户个人信息"'
            operationId: GetUserProfile
            responses:
                "200":
                    $ref: '#/responses/ProfileResp'
            summary: '"Get user''s profile | 获取用户个人信息"'
            tags:
                - user
        post:
            description: '"更新用户个人信息"'
            operationId: UpdateUserProfile
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/ProfileReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/SimpleMsg'
            summary: '"Update user''s profile | 更新用户个人信息"'
            tags:
                - user
    /user/register:
        post:
            description: '"注册"'
            operationId: Register
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/RegisterReq'
                    type: object
            responses:
                "200":
                    $ref: '#/responses/SimpleMsg'
            summary: '"Register | 注册"'
            tags:
                - user
produces:
    - application/json
responses:
    BaseMsgResp:
        description: The basic response without data | 基础不带数据信息
        headers:
            code:
                format: int32
                type: integer
            data:
                type: string
            msg:
                type: string
    RoleListResp:
        description: The response data of role list | 角色列表数据
        headers:
            total:
                description: The total number of data | 数据总数
                format: uint64
                type: integer
        schema:
            items:
                $ref: '#/definitions/RoleInfo'
            type: array
    SimpleMsgResp:
        description: The SimpleMsgResp | 简单信息Resp
        headers:
            msg:
                description: Message | 信息
                type: string
schemes:
    - http
    - https
security:
    - Token:
        - '[]'
securityDefinitions:
    Token:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
