name: Build Latest Image

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version to test'
        required: true
        default: 'latest'

jobs:
  build-slash-admin:
    runs-on: ubuntu-20.04
    env:
      IMAGE_REGISTRY: registry.cn-shenzhen.aliyuncs.com/go-slash/slash-admin
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: app/admin/cmd/api/Dockerfile
          push: true
          tags: registry.cn-shenzhen.aliyuncs.com/go-slash/slash-admin:${{ github.event.inputs.release-version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}